version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
         keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - dist
          key: v1-dist-{{ .Revision }}
  deploy:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - restore_cache:
          keys:
            - v1-dist-{{ .Revision }}
      - run:
          name: install now
          command: sudo npm i -g --unsafe-perm now
      - run:
          name: deploy to now
          command: now -t ${ZEIT_TOKEN} -A now.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
